---
git:
  submodules: false
bundler_args: --with postgres aws --without development debug
addons:
  chrome: stable
services:
  - mysql2
  - redis-server
  - postgresql
before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo rm -vf /etc/apt/sources.list.d/*hhvm*
  - sudo apt-get update
  - sudo apt-get install mediainfo
  - sudo ln -s /usr/bin/lsof /usr/sbin/lsof
  - gem install bundler -v $BUNDLER_VERSION
  - bundle config without development:production
before_script:
  - rm config/database.yml
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn install
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
language: ruby
jdk:
  - oraclejdk11
global_env:
  - BUNDLER_VERSION=2.0.1
  - JAVA_HOME=/home/travis/oraclejdk11  # just trying out, remove if doesn't work
rvm:
  - 2.6
node_js:
  - 12
dist: xenial
sudo: required
