name: CI RSpec Tests

on: [push, pull_request]

jobs:
  tests:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker compose
        run: docker-compose up test

      - name: Run Rspec specs
        run: docker-compose exec test bash -c "bundle exec rspec"
